name: Model Investor
favicon: null
layout_spectrum: 0.9887439699377865
typography_spectrum: 0.10976121621206403
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.18118240544572473
  lightness: 0.48208104562945664
  saturation: 0.7885744844097644
  rhythmicContrast: 0.1257784243207425
purpose: []
